info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: '{"code":200,"data":"welcome"}'
          schema:
            type: string
      tags:
      - 首页
  /user/getUserList:
    get:
      responses:
        "200":
          description: code","data"}
          schema:
            type: string
      tags:
      - User
swagger: "2.0"
